# Generated by Django 4.0.2 on 2022-07-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logins',
            name='username',
            field=models.CharField(max_length=300),
        ),
    ]
