# Generated by Django 4.0.2 on 2022-07-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_rename_username_register_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='password',
            new_name='password2',
        ),
    ]
